### PR TITLE
Dropdown for Upgrading /downgrading a DAO member status

### PR DESCRIPTION
**Pull request by amrro**
## Linear Ticket
[ENG-885](https://linear.app/govrn/issue/ENG-885/dropdown-for-upgrading-downgrading-a-dao-member-status).

## Description
- Add the ability to change the membership status of members. The available membership options are Recruit, Member, and Admin.
- Build upon the changes introduced in #439 PR.

### CODE REVIEW

**Review by jonathanprozzi — COMMENTED** [review]
This looks great on first read -- going to test and read through a bit more soon!

**Comment by jonathanprozzi** [comment]
Hmm, went to test this again and it's no longer showing up on the Settings page for me. I only see the previous version:

image

**Comment by amrro** [comment]
> Hmm, went to test this again and it's no longer showing up on the Settings page for me. I only see the previous version:
> 
> image

Thanks @jonathanprozzi. I made mistake earlier, but I have fixed it now and re-added the changes.
 
Short Horror Story: I kept committing from different PR on this PR, then force-pushed. 
apologies for any confusion this may have caused.

**Comment by jonathanprozzi** [comment]
> 

Oh no!! thanks for the update! Testing now 👍

**Comment by jonathanprozzi** [comment]
Also, wondering if we should merge in #439 before this? It looks like this uses the new SelectOption type @alexkeating

**Comment by alexkeating** [comment]
Closing for #448

**Pull request closed without merging**
