### PR TITLE
fix/redirect-flow-check (ENG-939) -- Hold on merge

### PR DESCRIPTION
**Pull request by jonathanprozzi**
## Linear Ticket

- [ENG-939](https://linear.app/govrn/issue/ENG-939/bug-user-can-interrupt-auth-flow-check)

## Description

- See ticket for details
- If we'd like, we can add in a specific Error view similar to the DAO users check. I opted for a redirect for now

### CODE REVIEW

**Comment by jonathanprozzi** [comment]
Noticing an issue with this when testing more -- refreshing takes back to the /

**Comment by jonathanprozzi** [comment]
Fixing this from our conversation @alexkeating

**Comment by alexkeating** [comment]
Should this pr be closed then?

**Comment by jonathanprozzi** [comment]
Let's close this and I'll reopen one when the new, more robust flow is in place.

**Pull request closed without merging**
