### PR TITLE
react-table v7 -> v8

### PR DESCRIPTION
**Pull request by amrro**
## Linear Ticket

Add the link to the Linear ticket here.

## Description

Brief description of the changes in the PR.

## Screencaptures

For frontend changes, considering adding a screenshot or screencapture of the changes.
Before/after screenshots may be helpful when relevant.

### CODE REVIEW

**Comment by jonathanprozzi** [comment]
image

i'm seeing this as the UI right now -- with everything going on this cycle I'm not sure we'd be able to fully work on this and integrate it. 

I agree that v7 isn't ideal but I'll need to take a bit of a deeper look into this since we're losing quite a lot of the current UX here

**Comment by amrro** [comment]
Yeah, it's missing styling from the theme. 
But if you want a rapid comparison between the two, check this: 
https://github.com/chakra-ui/chakra-ui/pull/6339/files

**Comment by jonathanprozzi** [comment]
This is a good starting point though, I can take a look at how we can leverage our existing styles for this since they're in our theme

**Comment by jonathanprozzi** [comment]
Oh I think if you can rebase / merge in the recent staging changes that'll help clean up the diffs too 

Digging into this to see how to approach the styles

**Comment by jonathanprozzi** [comment]
We can handle some of the styles without too much of a headache since they're in our theme already. 

The biggest areas we'd need to handle are replacing/refactoring the search(filter)/sort and the tableHooks that add in the actions (edit/delete and checkboxes for the select)

**Pull request closed without merging**
