### PR TITLE
add getContributionCount endpoint

### PR DESCRIPTION
**Pull request by Flip-Liquid**
## Linear Ticket
[Pro-527](https://linear.app/govrn/issue/PRO-527/create-a-getdaocontributioncount-endpoint)

## Description

Add `getContributionCount` endpoint 

## Screencaptures

For frontend changes, considering adding a screenshot or screencapture of the changes.
Before/after screenshots may be helpful when relevant.

### CODE REVIEW

**Comment by jonathanprozzi** [comment]
@Flip-Liquid nice! Works well for getting the total Contribution count by DAO. Passing in the filters as you described does exactly this.

Question I have while also thinking about PRO-478 (Contribution percent by Member in a Date Range)

If we change the return on this from an Int to either the ContributionFragment or something that includes the user (with id and name) we'd be able to use this for the pie chart showing Member % / Total %.

What do you think?

**Comment by Flip-Liquid** [comment]
@jonathanprozzi just making sure I understand correctly. you want to show a particular member their overall pctg contribution to the entire guild's contributions to visualize how big their slice of contributions are?

would you need the contribution fragment then? or e.g. just the # of contributions for the dao and # of contributions for the user?

**Comment by jonathanprozzi** [comment]
> @jonathanprozzi just making sure I understand correctly. you want to show a particular member their overall pctg contribution to the entire guild's contributions to visualize how big their slice of contributions are?
> 
> would you need the contribution fragment then? or e.g. just the # of contributions for the dao and # of contributions for the user?

Good questions - apologies for not being clear. That is the usecase -- It would be for this graph:

image

It's a pie showing each member's contribution % out of all contributions for the date range. Definitely right in that we wouldnt need the full Fragment -- just the total # for the member and for the DAO which you're returning with the count already.

**Comment by Flip-Liquid** [comment]
@jonathanprozzi also, would you need the user's display name returned along with the data? or is that already available on the FE?

**Review by alexkeating — APPROVED** [review]
Should be good after merge conflicts are resolved

**Comment by jonathanprozzi** [comment]
> 

We have the current user's display name -- we'll want the member names from each DAO if possible to include in the returned data

**Comment by jonathanprozzi** [comment]
Awesome! Once we get this merged in I'll wrap up the Contribution Count ticket too

**Pull request merged**
