### PR TITLE
Downgrade siwe

### PR DESCRIPTION
**Pull request by alexkeating**
## Linear Ticket

Add the link to the Linear ticket here.

### CODE REVIEW

**Review by jonathanprozzi — APPROVED** [review]
Thinking that the recent upgrade to 2 is causing issues on staging?

**Comment by jonathanprozzi** [comment]
I think we can switch out `SiweErrorType` with `ErrorTypes` -- this resolves the build issue for the `SiweErrorType`
Looking for the message issue now

**Comment by alexkeating** [comment]
> Thinking that the recent upgrade to 2 is causing issues on staging?

Could be I am testing it out

**Comment by jonathanprozzi** [comment]
Cool -- I was about to suggest validate instead of verify. Came across that too

Approved already. We can merge once CI is solid

**Comment by alexkeating** [comment]
> Cool -- I was about to suggest validate instead of verify. Came across that too
> 
> Approved already. We can merge once CI is solid

Yea, thanks I saw the errors in the build

**Pull request merged**
