### PR TITLE
feature/upgrade-react-18-chakra-v2

### PR DESCRIPTION
**Pull request by jonathanprozzi**
## Linear Ticket

- [PRO-435](https://linear.app/govrn/issue/PRO-435/upgrade-to-react-18)
- [PRO-437](https://linear.app/govrn/issue/PRO-437/upgrade-to-chakra-v2)

## Description

- Upgrades to React 18 and to Chakra v2
- Handled breaking changes in both upgrades (fairly minimal)
- Tested the following:
  - Frontend runs locally
  - Frontend builds
  - Frontend lint + tsc pass
  - UI Storybook runs locally
  - UI lint + tsc pass

Didn't encounter any issues with any of our packages or build processes, but going to monitor our CI for errors to see if I missed anything when testing.

### CODE REVIEW

**Review by alexkeating — APPROVED** [review]
Looks good, will merge if ci passes

**Comment by jonathanprozzi** [comment]
@alexkeating cool we got this working with the timeout change. Cypress passed, but now merging in staging since I didn't notice it was out of date before checking the tests so CI is running again. If cypress passes again I'll merge in 👍

**Comment by jonathanprozzi** [comment]
Strange, passed Cypress before I merged in staging and then failed on the second run after the update, but staging builds fine. Same timeout error even with us bumping it up.

**Comment by jonathanprozzi** [comment]
Wondering if there is something going on with the change to React 18 or Chakra v2 with regard to our tests. They're passing locally so unsure and we're using the latest version of the Cypress nx plugin, but going to do a bit of research into this.

**Comment by NKoech123** [comment]
I just ran it locally and it's strange how the test skips the line below:
Screen Shot 2022-09-30 at 2 44 22 PM
Let me investigate it further

**Pull request merged**
