### PR TITLE
Fix null usernames

### PR DESCRIPTION
**Pull request by alexkeating**
## Linear Ticket

https://linear.app/govrn/issue/PRO-663/show-0x-if-no-user-name

## Description

- Add address for null display name

### CODE REVIEW

**Comment by jonathanprozzi** [comment]
Awesome. I'm noticing that it's using this for my name as well even though my name is set. Going to test since I think it's because I may be using `name` -- will check that again.

CleanShot 2022-11-22 at 14 57 30

**Comment by jonathanprozzi** [comment]
Yup, that's exactly what it is -- I have my `name` set in my local db but not my `display_name` -- I think there may be other places where we use name instead of display_name

**Review by jonathanprozzi — APPROVED** [review]
Approved -- noting that we may want to think about our use of  `name` and `display_name` since I think we're using `name` at some places in the frontend

**Comment by alexkeating** [comment]
> Approved -- noting that we may want to think about our use of `name` and `display_name` since I think we're using `name` at some places in the frontend

Yea, I think we have a ticket about that

**Pull request merged**
